import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { StudentProvider } from "./contexts/studentContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* nav bar */}
        <nav className="bg-gray-800 text-white p-4">
          <div className="container mx-auto">
            <h1 className="text-xl font-bold">School Web App</h1>
            <ul className="flex space-x-4 mt-2">
              <li>
                <Link href="/" className="hover:underline">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/students?limit=3" className="hover:underline">
                  Students
                </Link>
              </li>
              <li>
                <Link href="/teachers" className="hover:underline">
                  Teachers
                </Link>
              </li>
              <li>
                <Link href="/moods" className="hover:underline">
                  Moods
                </Link>
              </li>
            </ul>
          </div>
        </nav>
        <StudentProvider>
          {children}
        </StudentProvider>
      </body>
    </html>
  );
}
